---
## Tor section
- name: restart tor
  service: name=tor state=restarted

## SecureDrop Interfaces
- name: restart apache2
  service: name=apache2 state=restarted

- name: reload supervisor
  supervisorctl:
    name: securedrop_worker
    state: present

