---
- hosts: [ 'mon-build' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/mon.yml
    - development-specific.yml

  roles:
    - { role: build-ossec-deb-pkg, tags: [ "ossec" ] }

  sudo: yes

- hosts: [ 'app-build' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/app.yml
    - development-specific.yml

  roles:
    - build-securedrop-app-code-deb-pkg
    - { role: build-ossec-deb-pkg, tags: [ "ossec" ] }

  sudo: yes
