---
- hosts: [ 'mon-build' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/mon.yml
    - staging-specific.yml

  roles:
    - build-ossec-deb-pkg

  sudo: yes

- hosts: [ 'app-build' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/app.yml
    - staging-specific.yml

  roles:
    - build-securedrop-app-code-deb-pkg
    - build-ossec-deb-pkg

  sudo: yes

