---
### Used by the common role ###
ssh_users: ""

# TODO Should use ansible to gather this info
monitor_ip: ""
monitor_hostname: ""
app_hostname: ""
app_ip: ""

### Used by the app role ###
securedrop_user: "www-data"
securedrop_code: "/var/www/securedrop"
# The securedrop_header_image has to be in the install_files/ansible-base/ or
# the install_files/ansible-base/roles/app/files/ directory
# Leave set to None to use the SecureDrop logo.
securedrop_header_image: "None"
# The app gpg public key has to be in the install_files/ansible-base/ or
# install_files/ansible-base/roles/app/files/ directory
securedrop_app_gpg_public_key: ""
securedrop_app_gpg_fingerprint: ""

### Used by the mon role ###
# The ossec alert gpg public key has to be in the install_files/ansible-base/ or
# install_files/ansible-base/roles/app/files/ directory
ossec_alert_gpg_public_key: ""
ossec_gpg_fpr: ""
ossec_alert_email: ""
smtp_relay: ""
smtp_relay_port: ""
smtp_relay_fingerprint: ""
sasl_username: ""
sasl_domain: ""
sasl_password: ""
# The ca_cert for the remote smtp relay needs to be in the
# install_files/ansible-base or install_files/ansible-base/mon/files directory
ca_cert: ""
