---
- hosts: [ 'mon' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/mon.yml
    - prod-specific.yml

  roles:
    #- validate
    - common
    - mon

  sudo: yes

- hosts: [ 'app' ]

  vars_files:
   - group_vars/securedrop.yml
   - host_vars/app.yml
   - prod-specific.yml

  vars:

  roles:
    #- validate
    - common
    - app

  sudo: yes

- hosts: [ 'mon-staging' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/mon.yml
    - staging-specific.yml

  roles:
    - remove_ossec_exemptions

  sudo: yes

- hosts: [ 'app-staging' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/app.yml
    - staging-specific.yml

  roles:
    - remove_ossec_exemptions
