---
- hosts: [ 'mon-staging' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/mon.yml
    - staging-specific.yml

  roles:
    - common
    - build-ossec-deb-pkg
    - mon
    - allow-direct-access

  sudo: yes
