---
- hosts: [ 'localhost' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/app.yml
    - travis-specific.yml

  roles:
    - { role: development, tags: development }
    - { role: app, tags: app }
    - { role: app-test, tags: app-test }

  sudo: yes
