---
- name: ensure securedrop-ossec-agent package is installed
  apt: name=securedrop-ossec-agent state=present

- stat: path=/var/ossec/etc/client.keys
  register: ossec_client_keys

- stat: path=/etc/network/iptables/rules_v4
  register: iptables_rules

- name: if agent is not already added add agent_auth firewall exmeptions rules
  lineinfile:
    dest: /etc/network/iptables/rules_v4
    # last line in the initial *filter stanza (which must come before any rules)
    # rules will be applied before the default rules defined in rules_v4 file
    insertafter: "^:LOGNDROP"
    regexp: "{{ item }}"
    line: "{{ item }}"
  notify:
    - reload iptables rules
  with_items: agent_auth_rules
  when: iptables_rules.stat.exists and not ossec_client_keys.stat.exists

- name: run agent auth
  shell: /var/ossec/bin/agent-auth -m {{ monitor_ip }} -p 1515 -A {{ app_hostname }}
  when: not ossec_client_keys.stat.exists

  # If the OSSEC agent auth iptable rule exemptions are in place remove them and
  # restart OSSEC. This order does matter. The app server's
  # ossec agent needs to restart to load the imported cert from authd and
  # connect to the ossec server. The monitor server's OSSEC server needs to
  # restart after the agent connects to correctly display the agent status.
- name: remove insecure ossec agent auth firewall exemptions
  lineinfile:
    state: absent
    dest: /etc/network/iptables/rules_v4
    line: "{{ item }}"
  register: removed_ossec_exemptions
  notify:
    - reload iptables rules
    - restart ossec
  with_items: agent_auth_rules
  when: iptables_rules.stat.exists
