---
- name: install libselinux-python (required for ansible on centos)
  yum:
    name: libselinux-python
    state: present

- name: install netcat (required for ssh proxy command)
  yum:
    name: nc
    state: present

- name: add tor rpm repo
  copy:
    src: torproject.repo
    dest: /etc/yum/repos.d/

- name: install tor package
  yum:
    name: tor
    state: latest
    update_cache: yes
