---
- name: install postfix
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: ossec_postfix_dependencies
  tags:
    - apt
    - postfix

- name: ensure postfix /etc/aliases is present and configured for ossec
  copy:
    src: aliases
    dest: /etc/aliases
  notify: update aliases
  tags:
    - postfix

- name: configure sasl password for smtp relay
  template:
    src: sasl_passwd
    dest: /etc/postfix/sasl_passwd
    mode: '0400'
  notify: update sasl_passwd db
  tags:
    - postfix
    - permissions

- name: ensure header_checks regex to strip smtp headers is present
  copy:
    src: header_checks
    dest: /etc/postfix/header_checks
  notify: postmap_header_checks
  tags:
    - postfix
    - hardening

- name: configure postfix main.cf
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
  notify: restart postfix
  tags:
    - postfix

# TODO - name: configure postfix proxy
