---
- name: install postfix
  apt: pkg=postfix state=latest

- name: ensure postfix /etc/aliases is present and configured for ossec
  copy:
    src: aliases
    dest: /etc/aliases
  notify: update aliases

- name: configure sasl password for smtp relay
  template:
    src: sasl_passwd
    dest: /etc/postfix/sasl_passwd
    mode: 0400
  notify: update sasl_passwd db

- name: ensure smtp relay ssl cert is present
  copy:
    src: "{{ ca_cert }}"
    dest: /etc/postfix/cacert.pem
    mode: 0400

- name: ensure header_checks regex to strip smtp headers is present
  copy:
    src: header_checks
    dest: /etc/postfix/header_checks
  notify: postmap_header_checks

- name: configure postfix main.cf
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
  notify: restart postfix

# TODO - name: configure postfix proxy
