---
## Tor section
- name: restart tor
  service: name=tor state=restarted

## SecureDrop Interfaces
- name: restart apache2
  service: name=apache2 state=restarted

- name: start xvfb
  service: name=xvfb state=started

## System Hardening
- name: restart ssh
  service: name=ssh state=restarted

- name: restart ossec
  service: name=ossec state=restarted

- name: restart postfix
  service: name=postfix state=restarted

- name: reload iptables rules
  shell: iptables-restore < /etc/network/iptables/rules_v4
