---
- name: allow direct SSH access in sshd config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "ListenAddress 127.0.0.1:22"
    line: "ListenAddress 0.0.0.0:22"
  notify:
    - restart ssh

  # The ssh allow rule needs to be the first exemption loaded or else will
  # break the install the first time the reload iptables rules handler is run
- name: allow direct SSH acccess in iptables rules
  lineinfile:
    dest: /etc/network/iptables/rules_v4
    # last line in the initial *filter stanza (which must come before any rules)
    insertafter: "^:LOGNDROP"
    line: "\n-A INPUT -p tcp --dport 22 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT\n-A OUTPUT -p tcp --sport 22 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  notify:
    - reload iptables rules

- name: allow direct source interface access in iptables rules
  lineinfile:
    dest: /etc/network/iptables/rules_v4
    # insert after ssh rule exemption to allow direct source interface in iptables
    # rules
    insertafter: "OUTPUT -p tcp --sport 22 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
    line: "\n-A INPUT -p tcp --dport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT\n-A OUTPUT -p tcp --sport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  notify:
    - reload iptables rules

- name: allow direct document interface access in iptables rules
  lineinfile:
    dest: /etc/network/iptables/rules_v4
    # insert after ssh rule exemption to allow direct document interface access in iptables
    # rules
    insertafter: "OUTPUT -p tcp --sport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
    line: "\n-A INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT\n-A OUTPUT -p tcp --sport 8080 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  notify:
    - reload iptables rules
