---
- name: insure securedrop ossec package is installed
  apt: pkg="{{ ossec_package_name }}" state=latest

- name: ensure /etc/hosts file with 
  template:
    src="hosts"
    dest="/etc/hosts"
    owner=root
    group=root
    mode=0644

- name: ensure ossec configuration file is installed
  copy:
    src=ossec.conf
    dest="{{ ossec_config_path }}"
    owner="{{ ossec_user }}"
    group="{{ ossec_group }}"
    mode=0440
  notify:
  - restart ossec

- meta: flush_handlers

- name: ensure ossec is running
  service: name=ossec state=running
