---
- name: install apt package deps for dev environment
  apt: pkg="{{ item }}" state=latest
  with_items: dev_deps

- name: install dev pip deps for dev env
  command: "pip install -r /vagrant/securedrop/requirements/dev-requirements.txt"
