---
## Install Tor
- include: install_tor.yml
  tags:
    - app
    - mon
    - staging

- include: app_configure_tor_hidden_services.yml
  tags:
    - app
    - staging

- include: mon_configure_tor_hidden_services.yml
  tags:
    - mon

## Install Interfaces
- include: install_fpf_repo.yml
  tags:
    - app
    - mon
    - staging

- include: install_apache.yml
  tags:
    - app
    - staging

- include: create_app_dirs.yml
  tags:
    - app
    - staging
    - development

# Staging source wsgi file has logging enabled
- include: staging_wsgi_files.yml
  tags:
    - staging

# The production source wsgi file has logging disabled
- include: app_wsgi_files.yml
  tags:
    - app

# Install the SD dependencies for either tor run from
# securedrop_repo (development)
# install from a local deb package found in the securedrop_repo (staging)
# install securedrop from the fpf repo

- include: dev_install_pip_apt_pkgs.yml
  tags:
    - development
    - debs

- include: staging_install_local_deb_pkgs.yml
  tags:
    - staging

- include: app_install_securedrop_app_code_from_repo.yml
  tags:
    - app

# Create the app gpg keyring and databse
- include: initialize_securedrop_app.yml
  tags:
    - app
    - staging
    - development

# For testing install the additional pip reqs.
- include: dev_setup_xvfb_for_functional_tests.yml
  tags:
    - development
    - staging
    - debs

# Start the webserver for development
- include: manage_py_start.yml
  tags:
    - development

## Build FPF debian packages
- include: build_debs.yml
  tags:
    - debs

## System Hardening
- include: unattended_upgrades.yml
  tags:
    - app
    - mon
    - staging
    - development

- include: sysctl.yml
  tags:
    - app
    - mon
    - staging

- include: create_users.yml
  tags:
    - app
    - staging

- include: apparmor_complain.yml
  tags:
    - staging
    - complain

- include: apparmor_enforce.yml
  tags:
    - app
    - enforce

- include: ssh.yml
  tags:
    - app
    - mon

- include: iptables.yml
  tags:
    - app

- include: display_onions.yml
  tags:
    - staging
    - tor

- include: configure_ossec.yml
  tags:
    - app
    - staging
    - ossec

#- include: configure_ossec_grsec.yml
#  tags:
#    - mon
#    - ossec

#- include: configure_grsec.yml
#  tags:
#      - app
#      - mon
#      - staging
#      - grsec
