---
- name: install postfix
  apt: pkg=postfix state=latest

- name: ensure postfix /etc/aliases is present and configured for ossec
  copy:
    src: aliases
    dest: /etc/aliases

- name: configure sasl password for smtp relay
  template:
    src: sasl_passwd
    dest: /etc/postfix/sasl_passwd
    mode: 0400

- name: postmap sasl_passwd
  command: "postmap /etc/postfix/sasl_passwd"

- name: ensure smtp relay ssl cert is present
  command: creates=/etc/postfix/cacert.pem cp {{ ca_cert }} /etc/postfix/cacert.pem

- name: configure postfix main.cf
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
  notify: restart postfix

#- name: configure postfix headers

#- name: configure postfix proxy


