---
- name: Install local securedrop-app-code deb package
  apt: deb="{{ securedrop_deb_path }}/{{ securedrop_app_code_deb }}.deb"
  tags:
    - securedrop-app-code

- name: Install local securedrop-ossec-agent deb package
  apt: deb="{{ securedrop_ossec_agent_deb }}.deb"
  tags:
    - ossec
