---
- name: ensure latest sudoers file is copied to sudoers.tmp
  copy:
    src="sudoers"
    dest=/etc/sudoers.tmp
    owner=root
    group=root
    mode=0440
  register: sudoers_st
  tags:
    - users
    - sudoers

- name: ensure sudoers file is installed if syntax check passes
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
  when: sudoers_st.changed
  tags:
    - users
    - sudoers

- name: ensure secureDrop admin user accounts exist
  user:
    name="{{ item }}"
    shell=/bin/bash
    groups=sudo,ssh
  with_items: ssh_users
  tags:
    - users
    - sudoers

- name: copy SecureDrop bashrc additions
  copy:
    src: bashrc_securedrop_additions
    dest: /etc/bashrc.securedrop_additions
    owner: root
    group: root
    mode: 0644
  tags:
    - users
    - environment

- name: add line to each users bashrc to source the SecureDrop additions
  lineinfile:
    dest: "/home/{{ item }}/.bashrc"
    line: ". /etc/bashrc.securedrop_additions"
    insertbefore: BOF
  with_items: ssh_users
  tags:
    - users
    - environment
