---
  # The ubuntu motd include displaying some system load averages.
  # this causes a grsec: From 10.0.2.2: denied RWX mmap of <anonymous mapping>
  # by /usr/bin/landscape-sysinfo[landscape-sysin:3393] uid/euid:0/0
  # gid/egid:0/0, parent
  # /usr/share/landscape/landscape-sysinfo.wrapper[50-landscape-sy:3386]
  # uid/euid:0/0 gid/egid:0/0
  # Disabling calling that script during login.
- name: remove motd pam module from ssh logins
  lineinfile: dest=/etc/pam.d/sshd regexp=pam.motd state=absent backup=yes
  tags:
    - motd
    - grsecurity

- name: install grsec predepends paxctl package
  apt: pkg=paxctl state=present
  tags:
    - apt
    - paxctl
    - kernel
    - hardening

- name: make the required grub paxctl changes
  command: paxctl -Cpm {{ item }}
  with_items: grub_pax
  tags:
    - paxctl
    - kernel
    - hardening

- name: install grsec package from fpf repo
  apt: pkg={{ grsec_package }} state=latest
  async: 300
  poll: 10
  tags:
    - apt
    - grsec
    - kernel
    - hardening

- name: get grsec kernel string
  shell: grep menuentry /boot/grub/grub.cfg | grep grsec | grep -v recovery | head -1 | cut -d "'" -f2
  register: grsec_str
  tags:
    - grsec
    - kernel
    - hardening

- name: set grsec kernel as default for next boot
  command: grub-reboot "Advanced options for Ubuntu>{{ grsec_str.stdout }}"
  tags:
    - grsec
    - kernel
    - hardening

- stat: path="/proc/sys/kernel/grsecurity/grsec_lock"
  register: running_grsec
  tags:
    - grsec
    - kernel
    - hardening

- name: reboot into the grsec kernel
  command: shutdown -r now "Rebooting into the grsec kernel..."
  async: 0
  poll: 0
  ignore_errors: true
  when: not running_grsec.stat.exists
  tags:
    - reboot
    - grsec
    - kernel
    - hardening

- name: waiting for server to come back
  local_action:
    module: wait_for
      host={{ ansible_ssh_host }}
      port={{ ansible_ssh_port }}
      delay=45
      state=started
  sudo: false
  when: not running_grsec.stat.exists
  tags:
    - reboot
    - grsec
    - kernel
    - hardening

- name: remove generic kernel metapackages
  apt: name=linux-signed-image-generic-lts-utopic state=absent
  apt: name=linux-signed-image-generic state=absent
  apt: name=linux-signed-generic-lts-utopic state=absent
  apt: name=linux-signed-generic state=absent
  tags: 
    - apt

- name: remove remaining generic kernels
  command: apt-get -y remove '^linux-image-.*generic$'
  tags: 
    - apt

- name: remove remaining kernel headers
  command: apt-get -y remove '^linux-headers-.*'
  tags: 
    - apt

- name: mark GRUB2 as manually installed so its not removed
  command: apt-mark manual grub-pc
  tags:
    - apt
    - kernel
    - grub

- name: cleanup any dependencies left
  command: apt-get -y autoremove
  tags:
    - apt
