---
- include: create_users.yml

- include: sysctl.yml

- include: harden_dns.yml

- include: remove_kernel_modules.yml

- include: install_tor.yml

  # Install Interfaces
- include: install_fpf_repo.yml

  # Install the grsec kernel prior to running unattended-upgrades to avoid
  # reboots
- include: from_fpf_repo_install_grsec.yml
  tags:
    - grsec

- include: unattended_upgrades.yml
  tags:
    - reboot

- include: apply_grsec_lock.yml
  tags:
    - reboot
    - grsec
