---
  # Since production environment does not have dhcp or dns create etc hosts
  # entries
- include: set_etc_hosts_for_prod_env.yml
  tags:
      # CI environment uses a vps where we use vagrant-hostmanger to manage
      # /etc/hosts
    - static-hosts

- include: install_tor.yml

  # Install Interfaces
- include: install_fpf_repo.yml

  # System Hardening
- include: unattended_upgrades.yml

- include: create_users.yml

- include: remove_kernel_modules.yml

- include: ssh.yml

- include: harden_dns.yml

- include: from_fpf_repo_install_grsec.yml
  tags:
    - grsec

# Needs to run after installing grsec kernel
- include: sysctl.yml
