---

securedrop_root: "/var/www/securedrop"
securedrop_data: "/var/lib/securedrop"

apache_user: "www-data"

apache_packages:
  - apache2-mpm-worker
  - libapache2-mod-wsgi
  - libapache2-mod-xsendfile

apache_files:
  - 'apache2.conf'
  - 'security'

apache_templates:
  - 'ports.conf'
  - 'sites-available/document.conf'
  - 'sites-available/source.conf'

apache_modules:
  - access_compat
  - authn_core
  - alias
  - authz_core
  - authz_host
  - authz_user
  - deflate
  - filter
  - dir
  - headers
  - mime
  - mpm_event
  - negotiation
  - reqtimeout
  - rewrite
  - wsgi
  - xsendfile

apache_disabled_modules:
  - auth_basic
  - authn_file
  - autoindex
  - env
  - setenvif
  - status

apache_sites:
  - source
  - document

app_deps:
  - gnupg2
  - haveged
  - python
  - python-pip
  - secure-delete
  - sqlite
  - apparmor-utils

dev_deps:
  - libssl-dev
  - python-dev
  - python-pip
