---
- name: download OSSEC
  get_url:
    url: http://www.ossec.net/files/ossec-hids-2.8.1.tar.gz
    dest: "{{ securedrop_repo }}"
    sha256sum: "03c073761aa484fe21a9fcc0ea318ba132ff2466c64360408046a4b8e527b529"

- name: install deb packages required to build ossec package
  apt: pkg="{{ item }}" state=latest
  with_items: build_ossec_deb_pkg_dependencies

- name: extract OSSEC archive to /tmp
  command: tar -xvf {{ ossec_archive }} -C /tmp

- name: ensure ossec /etc dir exists
  file:
    state: directory
    dest: /tmp/{{ ossec_version }}/etc

- name: copy ossec preloaded vars
  template:
    src: "{{ ossec_preloaded_vars }}"
    dest: /tmp/{{ ossec_version }}/etc/preloaded-vars.conf

- name: run ossec installer
  command: /tmp/{{ ossec_version }}/install.sh

- name: create ossec agent deb build dir
  file:
    state: directory
    dest: /tmp/{{ ossec_build_dir }}

- name: ensure the temp ossec build dir var directory exists
  file:
    state: directory
    dest: /tmp/{{ ossec_build_dir }}/var

- name: mv /var/ossec to ossec build dir
  command: cp -R /var/ossec /tmp/{{ ossec_build_dir }}/var/

- name: copy OSSEC agent DEBIAN dir to build dir
  command: cp -R {{ securedrop_repo }}/install_files/{{ossec_package_name}}/DEBIAN /tmp/{{ ossec_build_dir }}

- name: copy OSSEC agent usr dir to build dir
  command: cp -R {{ securedrop_repo }}/install_files/{{ossec_package_name}}/usr /tmp/{{ ossec_build_dir }}

- name: copy OSSEC agent var dir to build dir
  command: cp -R {{ securedrop_repo }}/install_files/{{ossec_package_name}}/var /tmp/{{ ossec_build_dir }}

- name: copy OSSEC agent etc dir to build dir
  command: cp -R {{ securedrop_repo }}/install_files/{{ossec_package_name}}/etc /tmp/{{ ossec_build_dir }}

- name: build securedrop ossec deb package
  command: dpkg-deb --build /tmp/{{ ossec_build_dir }}

- name: move securedrop ossec deb to repo
  command: mv /tmp/{{ ossec_build_dir }}.deb {{ securedrop_repo }}

- name: delete tmp build paths
  file:
    state: absent
    dest: /tmp/{{ ossec_build_dir }}

- name: delete tmp install paths
  file:
    state: absent
    dest: /tmp/{{ ossec_version }}

- name: install local securedrop ossec deb package
  apt: deb="{{ securedrop_repo }}/{{ ossec_build_dir }}.deb" state=installed
