---
- name: ensure logging enabled source wsgi app files exists
  copy: src=source.wsgi.logging dest=/var/www/source.wsgi owner={{ www-data }} mode=0640

- name: ensure logging enable document wsgi app file exists
  copy: src=document.wsgi.logging dest=/var/www/document.wsgi owner={{ www-data }} mode=0640
