---
- include: install_fpf_repo.yml
  tags:
    - app
    - mon
    - staging

- include: install_apache.yml
  tags:
    - app
    - staging

- include: create_app_dirs.yml
  tags:
    - app
    - staging
    - development

- include: prod_wsgi_files.yml
  tags:
     - app
     - staging

- include: dev_app_code_depends.yml
  tags:
    - development
    - debs

- include: staging_app_code.yml
  tags:
    - staging

- include: securedrop_app_code_deb.yml
  tags:
    - app

- include: install_app_deps.yml
  tags:
    - app
    - staging
    - development

- include: dev_setup_xvfb_for_functional_tests.yml
  tags:
    - development
    - debs

- include: build_debs.yml
  tags:
    - debs
