---
# Add dependency for FPF repo installation role.
dependencies:
  - { role: install-fpf-repo, when: not install_local_packages }
  - { role: grsecurity, when: grsecurity, tags: [grsec, grsecurity] }
  - tor-hidden-services
