---
  # This whole role is tag'd as restart and grsec. If the tag 'restart' is skipped none
  # of these tasks will run same for the grsec tag.

  # Check to ensure a restart is needed to apply sysctl grsec lock command
- stat: path="/proc/sys/kernel/grsecurity/grsec_lock"
  register: grsec_lock

- name: restart machine
  command: shutdown -r now "Ansible restart to boot into grsec kernel"
  async: 0
  poll: 0
  ignore_errors: true
  when: not grsec_lock.stat.exists
  sudo: yes

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port={{ ansible_ssh_port }} state=started
  when: not grsec_lock.stat.exists
  sudo: false

- sysctl: name=kernel.grsecurity.grsec_lock value=1 sysctl_set=yes state=present reload=yes
  when: grsec_lock.stat.exists
  sudo: yes
