---
- name: allow direct SSH access in sshd config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "ListenAddress 127.0.0.1:22"
    line: "ListenAddress 0.0.0.0:22"
  notify:
    - restart ssh

- name: allow direct SSH acccess in iptables rules
  lineinfile:
    dest: /etc/network/iptables/rules_v4
    # last line in the initial *filter stanza (which must come before any rules)
    # rules will be applied before the default rules defined in rules_v4 file
    insertafter: "^:LOGNDROP"
    regex: "{{ item }}"
    line: "{{ item }}"
  notify:
    - reload iptables rules
  with_items: direct_access_rules
