---
- name: ensure custom apparmor profiles are present
  file:
    state: link
    force: yes
    src: "{{ item }}"
    dest: /etc/apparmor.d/{{ item }}
  with_items: apparmor_profiles

- name: ensure custom appamror profiles are in complain mode
  command: "aa-complain /etc/apparmor.d/{{ item }}"
  with_items: apparmor_profiles 
