---
- include: staging_wsgi_files.yml
  tags:
    - apache
    - non-development

- include: apparmor_complain.yml
  tags:
    - aa-complain
    - non-development

- include: dev_setup_xvfb_for_functional_tests.yml

- include: security_hardening_tests.yml
  tags: non-development
