---
- name: wait for all tor hidden services hostname files
  wait_for:
    state: present
    path: "{{ tor_hidden_services_parent_dir }}/{{ item }}/hostname"
    delay: 5
  with_items: mon_tor_instances
  tags:
    - tor

- name: fetch securedrop ssh aths
  fetch:
    src: /var/lib/tor/services/ssh/hostname
    dest: ./mon-ssh-aths
    flat: yes
    fail_on_missing: yes
  tags:
    - tor
    - fetch
    - admin

  # These tasks modifies the fetched copy of the server's aths info to
  # format it for a torrc file on the admins workstation.
  # This should make it easier for the admin or journalist to copy paste the
  # line correctly.
- name: format mon ssh aths
  local_action: lineinfile
    dest=./mon-ssh-aths
    regexp='(.*)'
    backrefs=yes
    line='HidServAuth \1'
  sudo: no
  tags:
    - tor
    - admin
