---
## Tor
tor_distribution_release: "trusty"
tor_wait_for_hidden_services: yes
tor_hidden_services_parent_dir: "/var/lib/tor/services"
tor_user: debian-tor
tor_DataDirectory: /var/lib/tor
securedrop_tor_user: "debian-tor"

# Configuring the tor hidden services
app_tor_instances:
  - ssh
  - source
  - document

mon_tor_instances:
  - ssh

sshHost: "app"
sshHostnameFile: "{{ tor_hidden_services_parent_dir }}/ssh/hostname"
documentHostnameFile: "{{ tor_hidden_services_parent_dir }}/document/hostname"
sourceHostnameFile: "{{ tor_hidden_services_parent_dir }}/source/hostname"
document_user: "journalist"

# Defaults for installing the fpf repo
fpf_distribution_release: "trusty"

# Defaults for install_app_depends.yml tasks
headerFilePath: "{{ securedrop_header_image_path }}"
AppGPGPublicKey: "{{ securedrop_app_gpg_public_key_path }}"
AppGPGFingerprint: "{{ securedrop_app_gpg_fingerprint }}"

## Interface defaults
securedrop_data: "/var/lib/securedrop"
securedrop_code: "/var/www/securedrop"
securedrop_user: "www-data"

apache_user: "www-data"

apache_packages:
  - apache2-mpm-worker
  - libapache2-mod-wsgi
  - libapache2-mod-xsendfile

apache_files:
  - 'apache2.conf'
  - 'security'

apache_templates:
  - 'ports.conf'
  - 'sites-available/document.conf'
  - 'sites-available/source.conf'

apache_modules:
  - access_compat
  - authn_core
  - alias
  - authz_core
  - authz_host
  - authz_user
  - deflate
  - filter
  - dir
  - headers
  - mime
  - mpm_event
  - negotiation
  - reqtimeout
  - rewrite
  - wsgi
  - xsendfile

## TODO instead of hard coding disabled modules find intersection of
#apache_modules vs enabled modules
apache_disabled_modules:
  - auth_basic
  - authn_file
  - autoindex
  - env
  - setenvif
  - status

apache_sites:
  - source
  - document

app_deps:
  - gnupg2
  - haveged
  - python
  - python-pip
  - secure-delete
  - sqlite
  - apparmor-utils

dev_deps:
  - libssl-dev
  - python-dev
  - python-pip
  - firefox
  - xvfb

ossec_deb_pkg_dependencies:
  - inotify-tools
  - libssl-dev
  - make
  - tar
  - unzip

ossec_server_deb_pkg_dependencies:
    - inotify-tools
    - procmail
    - postfix
    - mailutils
    - adduser
    - expect
    - libc6

app_fpf_packages:
  - securedrop-app-code
  - securedrop-ossec-agent

mon_fpf_packages:
  - securedrop-ossec-server

# There only needs to be one ATHS for the document interface
document_aths:
  - journalist

# Build FPF deb packages

## System Hardening
app_apparmor_profiles:
  - usr.bin.tor
  - usr.lib.apache2.mpm-worker.apache2

distro_id: "ubuntu"
distro_codename: "trusty"

disabled_kernel_modules:
  - bluetooth
  - iwlwifi

ip_info:
  - ip: "{{ monitor_ip }}"
    hostname: "{{ monitor_hostname }} securedrop-monitor-server-alias"
  - ip: "{{ app_ip }}"
    hostname: "{{ app_ip }}"

sysctl_flags:
  - name: "net.ipv4.tcp_max_syn_backlog"
    value: "4096"
  - name: "net.ipv4.tcp_syncookies"
    value: "1"
  - name: "net.ipv4.conf.all.rp_filter"
    value: "1"
  - name: "net.ipv4.conf.all.accept_source_route"
    value: "0"
  - name: "net.ipv4.conf.all.accept_redirects"
    value: "0"
  - name: "net.ipv4.conf.all.secure_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.rp_filter"
    value: "1"
  - name: "net.ipv4.conf.default.accept_source_route"
    value: "0"
  - name: "net.ipv4.conf.default.accept_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.secure_redirects"
    value: "0"
  - name: "net.ipv4.icmp_echo_ignore_broadcasts"
    value: "1"
  - name: "net.ipv4.ip_forward"
    value: "0"
  - name: "net.ipv4.conf.all.send_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.send_redirects"
    value: "0"
  - name: "net.ipv6.conf.all.disable_ipv6"
    value: "1"
  - name: "net.ipv6.conf.default.disable_ipv6"
    value: "1"
  - name: "net.ipv6.conf.lo.disable_ipv6"
    value: "1"

ossec_group: "ossec"

# grsec vars
grub_pax:
  - /usr/sbin/grub-probe
  - /usr/sbin/grub-mkdevicemap
  - /usr/sbin/grub-setup
  - /usr/bin/grub-script-check
  - /usr/bin/grub-mount
