---
## Tor
tor_distribution_release: "trusty"
tor_wait_for_hidden_services: yes
tor_hidden_services_parent_dir: "/var/lib/tor/services"
tor_user: debian-tor
tor_DataDirectory: /var/lib/tor
securedrop_tor_user: "debian-tor"

# Configuring the tor hidden services
app_tor_instances:
  - ssh
  - source
  - document

mon_tor_instances:
  - ssh

sshHost: "app"
sshHostnameFile: "{{ tor_hidden_services_parent_dir }}/ssh/hostname"
documentHostnameFile: "{{ tor_hidden_services_parent_dir }}/document/hostname"
sourceHostnameFile: "{{ tor_hidden_services_parent_dir }}/source/hostname"
document_user: "journalist"

# Defaults for installing the fpf repo
fpf_distribution_release: "trusty"

# Defaults for install_app_depends.yml tasks
headerFilePath: "{{ securedrop_header_image_path }}"
AppGPGPublicKey: "{{ securedrop_app_gpg_public_key_path }}"
AppGPGFingerprint: "{{ securedrop_app_gpg_fingerprint }}"

# run_manage_py vars
manage_py_script: "{{ securedrop_code }}/manage.py start"

## Interface defaults
securedrop_data: "/var/lib/securedrop"
securedrop_code: "/var/www/securedrop"
securedrop_user: "www-data"

apache_user: "www-data"

apache_packages:
  - apache2-mpm-worker
  - libapache2-mod-wsgi
  - libapache2-mod-xsendfile

apache_files:
  - 'apache2.conf'
  - 'security'

apache_templates:
  - 'ports.conf'
  - 'sites-available/document.conf'
  - 'sites-available/source.conf'

apache_modules:
  - access_compat
  - authn_core
  - alias
  - authz_core
  - authz_host
  - authz_user
  - deflate
  - filter
  - dir
  - headers
  - mime
  - mpm_event
  - negotiation
  - reqtimeout
  - rewrite
  - wsgi
  - xsendfile

## TODO instead of hard coding disabled modules find intersection of
#apache_modules vs enabled modules
apache_disabled_modules:
  - auth_basic
  - authn_file
  - autoindex
  - env
  - setenvif
  - status

apache_sites:
  - source
  - document

app_deps:
  - gnupg2
  - haveged
  - python
  - python-pip
  - secure-delete
  - sqlite
  - apparmor-utils

dev_deps:
  - libssl-dev
  - python-dev
  - python-pip
  - firefox
  - xvfb

# There only needs to be one ATHS for the document interface
document_aths:
  - journalist

# Build FPF deb packages

## System Hardening
apparmor_profiles:
  - usr.bin.tor
  - usr.lib.apache2.mpm-worker.apache2

distro_id: "ubuntu"
distro_codename: "trusty"

# grsec vars
grub_pax:
  - /usr/sbin/grub-probe
  - /usr/sbin/grub-mkdevicemap
  - /usr/sbin/grub-setup
  - /usr/bin/grub-script-check
  - /usr/bin/grub-mount 
