---
## Tor
tor_distribution_release: "trusty"
tor_ExitPolicy: "reject *:*"
tor_hidden_services: "{{ securedrop_hidden_services }}"
tor_ReachableAddresses: "*:80,*:8080,*:443,*:8443,*:9001,*:9030"
tor_SafeLogging: 1
tor_wait_for_hidden_services: yes
tor_SocksPort: 0
tor_instance_parent_dir: /etc/tor/instances
tor_user: debian-tor
tor_DataDirectory: /var/lib/tor
tor_PidFile: /var/run/tor/tor.pid
tor_RunAsDaemon: 1
tor_Log: "notice file /var/log/tor/log"
tor_hidden_services_parent_dir: /var/lib/tor/services
tor_wait_for_hidden_services: no
securedrop_tor_user: "debian-tor"
hidden_services_parent_dir: "/var/lib/tor/services"

# Configuring the tor hidden services
service_ssh_port: 22
service_source_port: 80
service_document_port: 8080
sshEnv: "{{ securedrop_environment }}"
sshHost: "app"
sshHostnameFile: "{{ hidden_services_parent_dir }}/ssh/hostname"
documentHostnameFile: "{{ hidden_services_parent_dir }}/document/hostname"
sourceHostnameFile: "{{ hidden_services_parent_dir }}/source/hostname"
sshUsers: "{{ hidden_service_authorize_clients_list_key['ssh_users'].keys() }}"
sshPort: "{{ service_ssh_port }}"
sourcePort: "{{ service_source_port }}"
documentPort: "{{ service_document_port }}"

securedrop_hidden_services: [
  { dir: "source",
    ports:
      [{ virtport: "{{ service_source_port }}",
         target: "127.0.0.1:{{ service_source_port }}"
      }] 
  },
  { dir: "document",
    ports:
      [{
        virtport: "{{ service_document_port }}",
        target: "127.0.0.1:{{ service_document_port }}"
      }],
    HiddenServiceAuthorizeClients: "journalist"
  },
  { dir: "ssh",
    ports:
      [{
        virtport: "{{ service_ssh_port }}",
        target: "127.0.0.1:{{ service_ssh_port }}"
      }],
    HiddenServiceAuthorizeClients: "admin"
  }
]


# Defaults for installing the fpf repo
fpf_distribution_release: "trusty"

# Defaults for install_app_depends.yml tasks
headerFilePath: "{{ securedrop_header_image_path }}"
AppGPGPublicKey: "{{ securedrop_app_gpg_public_key_path }}"
AppGPGFingerprint: "{{ securedrop_app_gpg_fingerprint }}"

# run_manage_py vars
manage_py_script: "{{ securedrop_code }}/manage.py start"

## Interface defaults
securedrop_root: "/var/www/securedrop"
securedrop_data: "/var/lib/securedrop"
securedrop_user: "www-data"

apache_user: "www-data"

apache_packages:
  - apache2-mpm-worker
  - libapache2-mod-wsgi
  - libapache2-mod-xsendfile

apache_files:
  - 'apache2.conf'
  - 'security'

apache_templates:
  - 'ports.conf'
  - 'sites-available/document.conf'
  - 'sites-available/source.conf'

apache_modules:
  - access_compat
  - authn_core
  - alias
  - authz_core
  - authz_host
  - authz_user
  - deflate
  - filter
  - dir
  - headers
  - mime
  - mpm_event
  - negotiation
  - reqtimeout
  - rewrite
  - wsgi
  - xsendfile

## TODO instead of hard coding disabled modules find intersection of
#apache_modules vs enabled modules
apache_disabled_modules:
  - auth_basic
  - authn_file
  - autoindex
  - env
  - setenvif
  - status

apache_sites:
  - source
  - document

app_deps:
  - gnupg2
  - haveged
  - python
  - python-pip
  - secure-delete
  - sqlite
  - apparmor-utils

dev_deps:
  - libssl-dev
  - python-dev
  - python-pip
  - firefox
  - xvfb

build_deb_root:
  - /tmp/securedrop-debs

# There only needs to be one ATHS for the document interface
document_aths:
  - journalist


# Build FPF deb packages
build_deb_dirs:
  - securedrop-app-code
  - securedrop-python-mods
  - ossec-agent
  - ossec-server
  - securedrop-ossec-agent
  - securedrop-ossec-server

## System Hardening
apparmor_profiles:
  - usr.bin.tor
  - usr.lib.apache2.mpm-worker.apache2

distro_id: "ubuntu"
distro_codename: "trusty"
ossec_group: "ossec"
ossec_config_path: "{{ ossec_root }}/etc/ossec.conf"
ossec_package_name: "ossec-agent"
