---
- name: ensure /var/www/html/ is removed
  file:
    state: absent
    dest: "/var/www/html"
  tags:
    - apache
    - permissions

- name: ensure securedrop root directory exists
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_code }}"
  tags:
    - permissions

- name: ensure securedrop data directory exists
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_data }}"
  tags:
    - permissions

- name: ensure securedrop data store directory exists
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_data }}/store"
  tags:
    - permissions

- name: ensure securedrop keyring directory exists
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_data }}/keys"
  tags:
    - permissions

- name: ensure securedrop temp directory exists
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_data }}/tmp"
  tags:
    - permissions
