---
  # Since production environment do not have dhcp or dns set create etc hosts
  # entries
- include: set_etc_hosts_for_prod_env.yml
  tags:
    - not-snap

  # Repo and tor are installed in common role
- include: app_configure_tor_hidden_services.yml

- include: app_install_fpf_deb_pkgs.yml

- include: initialize_securedrop_app.yml

- include: harden_apache.yml

- include: app_iptables.yml

- include: app_display_onions.yml
