---
- name: add cron job to cleanup SecureDrop temp dir daily
  cron:
    name: cleanup SecureDrop temp dir
    # TODO: fullpath below should use {{ securedrop_code }} var
    job: "/var/www/securedrop/manage.py clean_tmp"
    special_time: daily
  tags:
    - cron
