---
# This role will upgrade 0.3pre instances to 0.3 instances.
# It will copy and run the upgrade.py script on the app and monitor servers.
- name: stop the apache service prior to upgrade tasks
  service: name=apache2 state=stopped
  when: server_role == 'app'
  sudo: yes

- name: copy upgrade script to servers
  copy: src="0.3pre_upgrade.py" dest="/tmp" owner="root" mode="740"
  sudo: yes

- name: run the upgrade script
  shell: "/tmp/0.3pre_upgrade.py {{ server_role }}"
  sudo: yes

- name: remove old 0.3 packages to avoid version error
  apt: name={{ item }} state=absent
  with_items:
    - securedrop-app-code
    - securedrop-grsec
    - securedrop-ossec-agent
    - securedrop-ossec-server
  sudo: yes

- name: remove the previous signing key
  apt_key: id=BD67D096 state=absent
  sudo: yes
