---
# This role will upgrade 0.3pre instances to 0.3 instances.
# It will copy and run the upgrade.py script on the app and monitor servers.

- name: copy upgrade script to servers
  copy: src="0.3pre_upgrade.py" dest="/tmp" owner="root" mode="740"
  sudo: yes

- name: run the upgrade script
  shell: "/tmp/0.3pre_upgrade.py {{ server_role }}"
  sudo: yes
