---
- name: allow direct SSH access in sshd config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "ListenAddress 127.0.0.1:22"
    line: "ListenAddress 0.0.0.0:22"
  notify:
    - restart direct access ssh
  meta: flush_handlers

- stat: path=/etc/network/iptables/rules_v4
  register: iptables_rules

- name: allow direct SSH acccess in iptables rules
  lineinfile:
    dest: /etc/network/iptables/rules_v4
    # last line in the initial *filter stanza (which must come before any rules)
    # rules will be applied before the default rules defined in rules_v4 file
    insertafter: "^:LOGNDROP"
    regexp: "{{ item }}"
    line: "{{ item }}"
  # Use a different handler name to avoid confusion since reloading iptables
  # for the allow direct access should be fire forget.
  # flush handlers so that this handler is ensured to be used before the
  # restrict direct access handler.
  notify:
    - reload direct access iptables
  meta: flush_handlers
  with_items: direct_access_rules
  when: iptables_rules.stat.exists
