---
build_ossec_deb_pkg_dependencies:
  - inotify-tools
  - libssl-dev
  - make
  - tar
  - unzip

ossec_group: "osseca"

ossec_apt_dependencies:
  - libc6
  - libssl1.0.0
  - expect
  - inotify-tools
  - adduser
