---
- name: wait for all tor hidden services hostname files
  wait_for: state=present path="{{ tor_hidden_services_parent_dir }}/{{ item }}/hostname" delay=5
  with_items: mon_tor_instances

- name: fetch securedrop ssh aths
  fetch: src=/var/lib/tor/services/ssh/hostname dest=./mon-ssh-aths flat=yes fail_on_missing=yes
