---
- name: update apt package lists
  apt: update_cache=yes

- name: install apt package deps for dev environment
  apt: pkg="{{ item }}" state=latest
  with_items: dev_deps

- name: install pip dependencies for securedrop
  pip: requirements="{{ securedrop_pip_requirements }}"

- name: set SECUREDROP_ENV in bashrc
  lineinfile:
    dest: /home/{{ securedrop_user }}/.bashrc
    state: present
    insertafter: EOF
    line: "export SECUREDROP_ENV=dev"
