---
- include: create_app_dirs.yml

- include: dev_install_pip_apt_pkgs.yml

- include: initialize_securedrop_app.yml

- include: dev_setup_xvfb_for_functional_tests.yml

- include: manage_py_start.yml
