---
## Dev flask debu webserver defaults
securedrop_data: "/var/lib/securedrop"
securedrop_code: "/vagrant/securedrop"
securedrop_repo: "/vagrant"

dev_deps:
  - libssl-dev
  - python-dev
  - python-pip
  - firefox
  - xvfb

app_deps:
  - gnupg2
  - haveged
  - python
  - python-pip
  - secure-delete
  - sqlite
  - apparmor-utils
