---
# Shared Variables
# Mon Variables
## Tor
tor_wait_for_hidden_services: yes
tor_hidden_services_parent_dir: "/var/lib/tor/services"
tor_user: debian-tor
tor_DataDirectory: /var/lib/tor
securedrop_tor_user: "debian-tor"

mon_tor_instances:
  - ssh

ossec_server_deb_pkg_dependencies:
    - inotify-tools
    - procmail
    - postfix
    - mailutils
    - adduser
    - expect
    - libc6

mon_fpf_packages:
  - securedrop-ossec-server
# Mon-test Variables
ip_info:
  - ip: "{{ monitor_ip }}"
    hostname: "{{ monitor_hostname }} securedrop-monitor-server-alias"
  - ip: "{{ app_ip }}"
    hostname: "{{ app_ip }}"


# Mon Debs Variables
build_ossec_deb_pkg_dependencies:
  - inotify-tools
  - libssl-dev
  - make
  - tar
  - unzip

ossec_group: "osseca"

ossec_apt_dependencies:
  - libc6
  - libssl1.0.0
  - expect
  - inotify-tools
  - adduser

# A alias is used by the app OSSEC agent's config. This way ansible doesn't
# need to modify a file that is being managed by  dpkg. This should ensure that
# any updates FPF push to the OSSEC configs will not require manual
# intervention.
ip_info:
  - ip: "{{ monitor_ip }}"
    hostname: "{{ monitor_hostname }} securedrop-monitor-server-alias"
  - ip: "{{ app_ip }}"
    hostname: "{{ app_hostname }}"
