---
tor_instance_parent_dir: /etc/tor/instances
tor_user: debian-tor
tor_DataDirectory: /var/lib/tor
tor_PidFile: /var/run/tor/tor.pid
tor_RunAsDaemon: 1
tor_Log: "notice file /var/log/tor/log"
tor_hidden_services_parent_dir: /var/lib/tor/services
tor_wait_for_hidden_services: no
