---

- name: ensure ssh configuration files are present
  copy: src={{ item }} dest=/etc/ssh/{{ item }} owner=root mode=0644
  with_items:
   - sshd_config
   - ssh_config
  notify:
   - restart ssh

- meta: flush_handlers

- name: ensure sshd is running
  service: name=ssh state=running
