---
- name: read in the onion addresses for ssh ATHS
  shell: "cat {{ sshHostnameFile }}"
  register: sshOnion
- name: read in the onion addresses for document ATHS
  shell: "cat {{ documentHostnameFile }}"
  register: documentOnion
- name: read in the onion addresses for source ATHS
  shell: "cat {{ sourceHostnameFile }}"
  register: sourceOnion

- name: print sshOnion address to stdout
  debug: msg="{{ sshOnion.stdout }}"
- name: print documentOnion address to stdout
  debug: msg="{{ documentOnion.stdout }}"
- name: print sourceOnion address to stdout
  debug: msg="{{ sourceOnion.stdout }}"

- name: set facts for "admin info" templates
  set_fact:
    sourceHost: "{{ sourceOnion.stdout }}"
    documentHost: "{{ documentOnion.stdout.split()[0] }}"
    sshHost: "{{ sourceOnion.stdout }}"
    documentAuthValue: "{{ documentOnion.stdout.split()[1] }}"
    sshAuthValue: "{{ sshOnion.stdout.split()[1] }}"

- name: create templated secureDropInfo
  template:
    src=secureDropInfo
    dest=/tmp/secureDropInfo
    mode=0700
- name: create templated secureDropATHS
  template:
    src=secureDropATHS
    dest=/tmp/secureDropATHS
    mode=0700

- name: fetch secureDropATHS
  fetch: src=/tmp/secureDropATHS dest=.
- name: remove tmp secureDropATHS
  file: state=absent path=/tmp/secureDropATHS

- name: fetch secureDropInfo
  fetch: src=/tmp/secureDropInfo dest=.
- name: remove tmp secureDropInfo
  file: state=absent path=/tmp/secureDropInfo
