---
- name: read in the ssh onion addresses for SSH ATHS
  shell: "cat {{ sshOnion_hostname }}"
  register: sshOnion
  tags:
    - production
    - staging

- name: print sshOnion address to stdout
  debug: msg="{{ sshOnion.stdout }}"
  tags:
    - production
    - staging

- name: copy ssh ATHS hostname file from guest to host
  fetch:
    flat: yes
    src: "{{ sshOnion_hostname }}"
    dest: "ssh-hostname"
  tags:
    - staging
 
- include: ssh.yml
  tags:
    - production
    - staging

- name: ensure 50unattended-upgrades is installed
  template: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/ mode=0400

- name: ensure 20auto-upgrades is installed
  copy: src=20auto-upgrades dest=/etc/apt/apt.conf.d/ mode=0400

- name: ensure sysctl.conf file exists
  copy: src=sysctl.conf dest=/etc/sysctl.conf mode=0400

- name: load sysctl.conf
  command: "sysctl -p /etc/sysctl.conf"

- include: iptables.yml
  tags:
    - production
    - staging

- include: create_users.yml
  tags:
    - production
    - staging
