---
- include: unattended_upgrades.yml
  tags:
    - production
    - staging
    - development

- include: sysctl.yml
  tags:
    - production
    - staging
    - development

- include: create_users.yml
  tags:
    - production
    - staging

- include: dev_apparmor_profiles.yml
  tags:
    - devlopment

- include: enforce_apparmor_profiles.yml
  tags:
    -staging

- include: ssh.yml
  tags:
    - production

- include: iptables.yml
  tags:
    - production

- include: display_onions.yml
  tags:
    - staging
    - development
    - tor

#- include: configure_ossec.yml
#  tags:
#    - production
#    - staging
