---
- name: read in the ssh onion addresses for SSH ATHS
  shell: "cat {{ sshOnion_hostname }}"
  register: sshOnion

- name: print sshOnion address to stdout
  debug: msg="{{ sshOnion.stdout }}"

- name: copy ssh ATHS hostname file from guest to host
  fetch:
    flat: yes
    src: "{{ sshOnion_hostname }}"
    dest: "ssh-hostname"

- include: ssh.yml
#  when: sshEnv == "prod" or sshEnv == "stag"

- name: ensure 50unattended-upgrades is installed
  template: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/ mode=0400

- name: ensure 20auto-upgrades is installed
  copy: src=20auto-upgrades dest=/etc/apt/apt.conf.d/ mode=0400
