---
- include: unattended_upgrades.yml
  tags:
    - production
    - staging
    - development

- include: sysctl.yml
  tags:
    - production
    - staging
    - development

- include: create_users.yml
  tags:
    - production
    - staging

- include: configure_ossec.yml
  tags:
    - production
    - staging

- include: ssh.yml
  tags:
    - production

- include: iptables.yml
  tags:
    - production

- include: display_onions.yml
  tags:
    - staging
