---
- include: unattended_upgrades.yml
  tags:
    - app
    - mon
    - staging
    - development

- include: sysctl.yml
  tags:
    - app
    - mon
    - staging

- include: create_users.yml
  tags:
    - app
    - staging

- include: enforce_apparmor_profiles.yml
  tags:
    - staging

- include: ssh.yml
  tags:
    - app
    - mon

- include: iptables.yml
  tags:
    - app

- include: display_onions.yml
  tags:
    - staging
    - development
    - tor

- include: configure_ossec.yml
  tags:
    - app
    - staging
    - ossec

#- include: configure_grsec.yml
#  tags:
#      - app
#      - mon
#      - staging
#      - grsec
