---
- name: ensure ssh configuration files are present
  copy: src={{ item }} dest=/etc/ssh/{{ item }} owner=root mode=0644
  with_items:
   - sshd_config
   - ssh_config
  notify:
   - restart ssh

- meta: flush_handlers

- name: ensure sshd is running
  service: name=ssh state=running

- name: ensure pam config is installed
  copy: src="common-auth" dest="/etc/pam.d/" owner=root mode=0644

- name: ensure google-authenticator configuration is present
  template:
    src="google_authenticator"
    dest="/home/{{ item }}/.google_authenticator"
    mode=0400
    owner="{{ item }}"
    group="{{ item }}"
  with_items: sshUsers


